# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: candis/mongo-replica-set:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports: 
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - ./.docker/mongodb:/data/db
      

    
  